/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafeteria;
import java.util.ArrayList;

/**
 *
 * @author Richa
 */
public class DesayunoTipico extends javax.swing.JPanel {

    /**
     * Creates new form DesayunoTipico
     */
    public DesayunoTipico() {
        initComponents();
    }

    
    public String getIngredientes() {
        
        String ingredientes = "";
        
        if (cbxQueso.isSelected()){
            ingredientes += "+Queso";
        } 
        if (cbxAguacate.isSelected()){
            ingredientes += "+Aguacate";
        }
        
        if (cbxCrema.isSelected()){
            ingredientes += "Crema";
        }
        
        if (cbxTocino.isSelected()){
            ingredientes += "+Tocino";
        }
        return ingredientes;
    }
    
    public int getPreciosTotal() {
        int total = 0; // base del omelette (ejemplo)

        if (cbxQueso.isSelected()) total += 5;
        if (cbxCrema.isSelected()) total += 5;
        if (cbxTocino.isSelected()) total += 5;
        if (cbxAguacate.isSelected()) total += 5;

        return total;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxQueso = new javax.swing.JCheckBox();
        cbxCrema = new javax.swing.JCheckBox();
        cbxTocino = new javax.swing.JCheckBox();
        cbxAguacate = new javax.swing.JCheckBox();

        cbxQueso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxQueso.setText("Queso Q5");

        cbxCrema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxCrema.setText("Crema Q5");

        cbxTocino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxTocino.setText("Tocino Q5");

        cbxAguacate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxAguacate.setText("Aguacate Q5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxTocino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxAguacate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxCrema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxQueso)
                    .addComponent(cbxCrema))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTocino)
                    .addComponent(cbxAguacate))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean tieneAguacate() {
        return cbxAguacate.isSelected();
    }

    public boolean tieneCrema() {
        return cbxCrema.isSelected();
    }

    public boolean tieneQueso() {
        return cbxQueso.isSelected();
    }   

    public boolean tieneTocino() {
        return cbxTocino.isSelected();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxAguacate;
    private javax.swing.JCheckBox cbxCrema;
    private javax.swing.JCheckBox cbxQueso;
    private javax.swing.JCheckBox cbxTocino;
    // End of variables declaration//GEN-END:variables
}
