/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeteria;

import javax.swing.JOptionPane;

/**
 *
 * @author Richa
 */
public class MenuCafes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCafes.class.getName());

    /**
     * Creates new form MenuCafes
     */
    public MenuCafes() {
        initComponents();
    }
    
    String nombreCliente = "";
    
    private Menu menuPrincipal;
    public MenuCafes(Menu menuPrincipal, String nombreCliente){
        this.menuPrincipal = menuPrincipal;
        this.nombreCliente = nombreCliente;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioMocha = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioIceCafe = new javax.swing.JRadioButton();
        radioMacchiato = new javax.swing.JRadioButton();
        radioEsspresso = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        agregarPedido = new javax.swing.JButton();
        radioCappuccino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioLatte = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cbxAzucar = new javax.swing.JCheckBox();
        cbxGalleta = new javax.swing.JCheckBox();
        cbxLeche = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        cantidadProducto = new javax.swing.JSpinner();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("más leche, sabor suave");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Pequeño, fuerte, base de casi todo");

        buttonGroup1.add(radioMocha);
        radioMocha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioMocha.setText("Mocha Q18");
        radioMocha.addActionListener(this::radioMochaActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("café frío con hielo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Que desea ordenar?");
        jLabel2.setToolTipText("");

        buttonGroup1.add(radioIceCafe);
        radioIceCafe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioIceCafe.setText("Iced Coffee Q20");
        radioIceCafe.addActionListener(this::radioIceCafeActionPerformed);

        buttonGroup1.add(radioMacchiato);
        radioMacchiato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioMacchiato.setText("Macchiato Q20");
        radioMacchiato.addActionListener(this::radioMacchiatoActionPerformed);

        buttonGroup1.add(radioEsspresso);
        radioEsspresso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioEsspresso.setText("Esspresso Q15");
        radioEsspresso.addActionListener(this::radioEsspressoActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("espresso con un toque de leche");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pequeño, fuerte, base de casi todo");

        agregarPedido.setText("Agregar al pedido");
        agregarPedido.addActionListener(this::agregarPedidoActionPerformed);

        buttonGroup1.add(radioCappuccino);
        radioCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioCappuccino.setText("Cappuccino Q20");
        radioCappuccino.addActionListener(this::radioCappuccinoActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("café + leche + espuma (clásico)");

        buttonGroup1.add(radioLatte);
        radioLatte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioLatte.setText("Latte Q12");
        radioLatte.addActionListener(this::radioLatteActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Extras");

        cbxAzucar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxAzucar.setText("Azucar extra (Q5)");
        cbxAzucar.addActionListener(this::cbxAzucarActionPerformed);

        cbxGalleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxGalleta.setText("Galleta (Q10)");
        cbxGalleta.setToolTipText("");
        cbxGalleta.addActionListener(this::cbxGalletaActionPerformed);

        cbxLeche.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxLeche.setText("Leche extra (Q10)");
        cbxLeche.addActionListener(this::cbxLecheActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Cantidad:");

        cantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(agregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel8))
                                            .addComponent(radioIceCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioMacchiato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxAzucar)
                                    .addComponent(cbxLeche))
                                .addGap(32, 32, 32)
                                .addComponent(cbxGalleta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioEsspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addComponent(radioCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioEsspresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioMocha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioCappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addComponent(radioIceCafe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioLatte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)))
                    .addComponent(radioMacchiato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLeche)
                    .addComponent(cbxGalleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAzucar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMochaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMochaActionPerformed

    private void radioIceCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIceCafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioIceCafeActionPerformed

    private void radioMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMacchiatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMacchiatoActionPerformed

    private void radioEsspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEsspressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEsspressoActionPerformed

    private void radioCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCappuccinoActionPerformed

    private void radioLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLatteActionPerformed

    private void cbxAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAzucarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAzucarActionPerformed

    private void cbxGalletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGalletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGalletaActionPerformed

    private void cbxLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLecheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLecheActionPerformed

    private void agregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoActionPerformed
        String nombre = "";
        String nombreExtra = "";
        double precioExtra = 0;
        int cantidad = 0;
        double precio = 0;
        
        
        if (radioEsspresso.isSelected()){
            nombre = "Esspresso";
            precio = 15;
        } else if (radioCappuccino.isSelected()){
            nombre = "Cappuccino";
            precio = 20;
        }  else if (radioLatte.isSelected()){
            nombre = "Latte";
            precio = 12;
        } else if (radioMocha.isSelected()){
            nombre = "Mocha";
            precio = 18;
        } else if (radioIceCafe.isSelected()){
            nombre = "Iced Coffee";
            precio = 20;
        } else if (radioMacchiato.isSelected()){
            nombre = "Macchiato";
            precio = 20;
        }
        
        
        if(cbxLeche.isSelected()){
            nombreExtra += " + Leche";
            precioExtra += 10;
        }
        
        if (cbxAzucar.isSelected()){
            nombreExtra += " + Azucar";
            precioExtra += 5;
        }
        
        if (cbxGalleta.isSelected()){
            nombreExtra += " + Galleta";
            precioExtra += 10;
        }
        
        cantidad = (int) cantidadProducto.getValue();
        
        if (nombre.isEmpty() || cantidad <= 0){
            if (nombre.isEmpty()){
                JOptionPane.showMessageDialog(null, "No has seleccionado ningun producto");
            } else {
                JOptionPane.showMessageDialog(null, "Cantidad no valida");
            }
            
        } else {
            Pedido p = new Pedido(nombre, cantidad, precio, nombreExtra, precioExtra);
            ListaPedidos.lista.add(p);
            
            if (menuPrincipal != null){
                menuPrincipal.actualizarBotonPagar();
                menuPrincipal.actualizarPedido();
            }
            
            this.dispose();
        }
        
    }//GEN-LAST:event_agregarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCafes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JSpinner cantidadProducto;
    private javax.swing.JCheckBox cbxAzucar;
    private javax.swing.JCheckBox cbxGalleta;
    private javax.swing.JCheckBox cbxLeche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton radioCappuccino;
    private javax.swing.JRadioButton radioEsspresso;
    private javax.swing.JRadioButton radioIceCafe;
    private javax.swing.JRadioButton radioLatte;
    private javax.swing.JRadioButton radioMacchiato;
    private javax.swing.JRadioButton radioMocha;
    // End of variables declaration//GEN-END:variables
}
