/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafeteria;

import javax.swing.JOptionPane;

/**
 *
 * @author Richa
 */
public class MenuDesayunos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuDesayunos.class.getName());

    /**
     * Creates new form MenuDesayunos
     */
    public MenuDesayunos() {
        initComponents();
    }
    
    String nombreCliente = "";
    private Menu menuPrincipal;
    public MenuDesayunos(Menu menuPrincipal, String nombreCliente){
        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.nombreCliente = nombreCliente;
    }
    public void ocultarPaneles(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupDesayunos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdDesayunoTipico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdPancakes = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rdOmelette = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdSandwich = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        agregarDesayuno = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Que desea ordenar?");

        groupDesayunos.add(rdDesayunoTipico);
        rdDesayunoTipico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdDesayunoTipico.setText("Desayuno típico Q30");
        rdDesayunoTipico.addActionListener(this::rdDesayunoTipicoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("huevos + frijoles + plátano + tortillas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("pancakes + miel");

        groupDesayunos.add(rdPancakes);
        rdPancakes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdPancakes.setText("Pancakes Q20");
        rdPancakes.addActionListener(this::rdPancakesActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("huevo");

        groupDesayunos.add(rdOmelette);
        rdOmelette.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdOmelette.setText("Omelette Q20");
        rdOmelette.addActionListener(this::rdOmeletteActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("pan + jamón + queso");

        groupDesayunos.add(rdSandwich);
        rdSandwich.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdSandwich.setText("Sandwich desayuno Q15");
        rdSandwich.addActionListener(this::rdSandwichActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Extras");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        agregarDesayuno.setText("Agregar pedido");
        agregarDesayuno.addActionListener(this::agregarDesayunoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdPancakes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdOmelette, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdSandwich)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rdDesayunoTipico))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdDesayunoTipico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdOmelette)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdPancakes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdSandwich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(agregarDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cambiarPanel(javax.swing.JPanel panel) {
        panelMenu.removeAll();
        panelMenu.setLayout(new java.awt.BorderLayout());
        panelMenu.add(panel, java.awt.BorderLayout.CENTER);
        panelMenu.revalidate();
        panelMenu.repaint();
    }
    
    
    private DesayunoTipico panelDesayuno;
    private Pancakes panelPancakes;
    private Omelett panelOmelet;
    private Sandwich panelSandwich;
    
    private void rdDesayunoTipicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDesayunoTipicoActionPerformed
        panelDesayuno = new DesayunoTipico();
        cambiarPanel(panelDesayuno); 
    }//GEN-LAST:event_rdDesayunoTipicoActionPerformed

    private void rdPancakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPancakesActionPerformed
        panelPancakes = new Pancakes();
        cambiarPanel(panelPancakes);
    }//GEN-LAST:event_rdPancakesActionPerformed

    private void rdOmeletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOmeletteActionPerformed
        panelOmelet = new Omelett();
        cambiarPanel(panelOmelet);
    }//GEN-LAST:event_rdOmeletteActionPerformed

    private void rdSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSandwichActionPerformed
        panelSandwich = new Sandwich();
        cambiarPanel(panelSandwich);
    }//GEN-LAST:event_rdSandwichActionPerformed

    private void agregarDesayunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDesayunoActionPerformed
        String nombre = "";
        String nombreExtra = "";
        int cantidad = 0;
        double precio = 0;
        double precioExtra = 0;
        
        if (rdDesayunoTipico.isSelected()){
            nombre = "Desayuno tipico";
            precio = 30;
            
            if (panelDesayuno != null){
                nombreExtra = panelDesayuno.getIngredientes();
                precioExtra = panelDesayuno.getPreciosTotal();
            }
            
        } else if (rdPancakes.isSelected()){
            nombre = "Pancakes";
            precio = 20;
            
            if (panelPancakes != null){
                nombreExtra = panelPancakes.getIngredientes();
                precioExtra = panelPancakes.getPreciosTotal();
            }            
            
        } else if (rdSandwich.isSelected()){
            nombre = "Sandiwch";
            precio = 15;
            
            if (panelSandwich != null){
                nombreExtra = panelSandwich.getIngredientes();
                precioExtra = panelSandwich.getPreciosTotal();
            } 
            
        } else if (rdOmelette.isSelected()){
            nombre = "Omelette";
            precio = 20;

            if (panelOmelet != null){
                nombreExtra = panelOmelet.getIngredientes();
                precioExtra = panelOmelet.getPreciosTotal();
            } 
            
        }
        
        cantidad = (int) jSpinner1.getValue();
        
        if (nombre.isEmpty() || cantidad <= 0){
            if (nombre.isEmpty()){
                JOptionPane.showMessageDialog(null, "No has seleccionado ningun producto");
            } else {
                JOptionPane.showMessageDialog(null, "Cantidad no valida");
            }
        } else {
            Pedido p = new Pedido(nombre, cantidad, precio, nombreExtra, precioExtra);
            ListaPedidos.lista.add(p);
                   
            if (menuPrincipal != null){
                menuPrincipal.actualizarBotonPagar();
                menuPrincipal.actualizarPedido();
            }
            
            this.dispose();            
        }
        
        
    }//GEN-LAST:event_agregarDesayunoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuDesayunos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarDesayuno;
    private javax.swing.ButtonGroup groupDesayunos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JRadioButton rdDesayunoTipico;
    private javax.swing.JRadioButton rdOmelette;
    private javax.swing.JRadioButton rdPancakes;
    private javax.swing.JRadioButton rdSandwich;
    // End of variables declaration//GEN-END:variables
}
