/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafeteria;

/**
 *
 * @author Richa
 */
public class Omelett extends javax.swing.JPanel {

    /**
     * Creates new form Omelett
     */
    public Omelett() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxQueso = new javax.swing.JCheckBox();
        cbxTomate = new javax.swing.JCheckBox();
        cbxChampi = new javax.swing.JCheckBox();
        cbxJamo = new javax.swing.JCheckBox();

        cbxQueso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxQueso.setText("Queso Q5");

        cbxTomate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxTomate.setText("Tomate Q5");

        cbxChampi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxChampi.setText("Champiñon Q5");

        cbxJamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxJamo.setText("Jamón Q5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxTomate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxQueso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addComponent(cbxJamo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addComponent(cbxChampi, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxQueso)
                    .addComponent(cbxJamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTomate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxChampi)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getIngredientes(){
        String ingredientes = "";
        
        if(cbxChampi.isSelected()){
            ingredientes += "+Champiñon ";
        }
        
        if(cbxJamo.isSelected()){
            ingredientes += "+Jamón ";
        }
        
        if (cbxQueso.isSelected()){
            ingredientes += "+Jamon ";
        }
        
        if(cbxTomate.isSelected()){
            ingredientes += "+Tomate ";
        }
        return ingredientes;
    }
    
    public double getPreciosTotal(){
        double total = 0;
        
        if(cbxChampi.isSelected()) total += 5;
        if(cbxJamo.isSelected()) total += 5;
        if (cbxQueso.isSelected()) total += 5;
        if(cbxTomate.isSelected()) total += 5;      
        
        return total;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxChampi;
    private javax.swing.JCheckBox cbxJamo;
    private javax.swing.JCheckBox cbxQueso;
    private javax.swing.JCheckBox cbxTomate;
    // End of variables declaration//GEN-END:variables
}
