/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafeteria;

/**
 *
 * @author Richa
 */
public class Pancakes extends javax.swing.JPanel {

    /**
     * Creates new form Pancakes
     */
    public Pancakes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxFruta = new javax.swing.JCheckBox();
        cbxCrema = new javax.swing.JCheckBox();
        cbxChocolate = new javax.swing.JCheckBox();
        cbxHelado = new javax.swing.JCheckBox();

        cbxFruta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxFruta.setText("Fruta Q10");

        cbxCrema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxCrema.setText("Crema batida Q7");

        cbxChocolate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxChocolate.setText("Chocolate Q5");

        cbxHelado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxHelado.setText("Helado Q10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCrema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxFruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxHelado)
                    .addComponent(cbxChocolate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCrema)
                    .addComponent(cbxHelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFruta)
                    .addComponent(cbxChocolate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getIngredientes(){
        String ingredientes = "";
        
        if (cbxCrema.isSelected()){
            ingredientes += "+Crema ";
        }
        
        if (cbxFruta.isSelected()){
            ingredientes += "+Fruta ";
        }
        
        if (cbxHelado.isSelected()){
            ingredientes += "+Helado ";
        }
        
        if (cbxChocolate.isSelected()){
            ingredientes += "Chocolate ";
        }
        
        return ingredientes;
    }
    
    public double getPreciosTotal(){
        double total = 0;
        
        if (cbxCrema.isSelected()) total += 7;
        if (cbxFruta.isSelected()) total += 10;
        if (cbxHelado.isSelected()) total += 10;
        if (cbxChocolate.isSelected()) total += 5;
        
        return total;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxChocolate;
    private javax.swing.JCheckBox cbxCrema;
    private javax.swing.JCheckBox cbxFruta;
    private javax.swing.JCheckBox cbxHelado;
    // End of variables declaration//GEN-END:variables
}
