/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafeteria;

/**
 *
 * @author Richa
 */
public class Sandwich extends javax.swing.JPanel {

    /**
     * Creates new form Sandwich
     */
    public Sandwich() {
        initComponents();
    }

    public String getIngredientes(){
        String ingredientes = "";
        
        if(cbxhuevo.isSelected()){
            ingredientes += "+Huevo ";
        }
        
        if (cbxAguacate.isSelected()){
            ingredientes += "+Aguacate ";
        }
        
        if (cbxSalsas.isSelected()){
            ingredientes += "+Salsas ";
        }
        
        if(cbxTocino.isSelected()){
            ingredientes += "+Tocino ";
        }
        
        return ingredientes;
    }
    
    public double getPreciosTotal(){
        double total = 0;
        
        if(cbxhuevo.isSelected()) total += 5;
        if (cbxAguacate.isSelected()) total += 5;
        if (cbxSalsas.isSelected()) total += 5;
        if(cbxTocino.isSelected()) total += 5;
            
        return total;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSandwich = new javax.swing.JPanel();
        cbxhuevo = new javax.swing.JCheckBox();
        cbxTocino = new javax.swing.JCheckBox();
        cbxAguacate = new javax.swing.JCheckBox();
        cbxSalsas = new javax.swing.JCheckBox();

        cbxhuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxhuevo.setText("Huevo Q5");

        cbxTocino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxTocino.setText("Tocino Q5");

        cbxAguacate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxAguacate.setText("Aguacate Q5");

        cbxSalsas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxSalsas.setText("Salsas Q5");

        javax.swing.GroupLayout panelSandwichLayout = new javax.swing.GroupLayout(panelSandwich);
        panelSandwich.setLayout(panelSandwichLayout);
        panelSandwichLayout.setHorizontalGroup(
            panelSandwichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSandwichLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSandwichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbxAguacate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxhuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTocino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSandwichLayout.setVerticalGroup(
            panelSandwichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSandwichLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSandwichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxhuevo)
                    .addComponent(cbxSalsas))
                .addGap(18, 18, 18)
                .addComponent(cbxAguacate)
                .addGap(18, 18, 18)
                .addComponent(cbxTocino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxAguacate;
    private javax.swing.JCheckBox cbxSalsas;
    private javax.swing.JCheckBox cbxTocino;
    private javax.swing.JCheckBox cbxhuevo;
    private javax.swing.JPanel panelSandwich;
    // End of variables declaration//GEN-END:variables
}
